### PR TITLE
Update VenuesPage.vue

### PR DESCRIPTION
**Pull request by jabarca99**
I wrote all the logic of the filters and copy the style of the accomodation page.

### CODE REVIEW

**Comment by Mexaby** [comment]
Sweet. Change the data to match that of the venue selection, i.e. if you select restaurants, only restaurants show up as results.

**Comment by jabarca99** [comment]
I commited the new changes. Some changes on VenuesPage, I added to the index the new vue (VenueDetails.vue and VenueList.vue), i created a new class called venues.js linked with VenueList and i added all the photos of the venues folders

**Comment by Mexaby** [comment]
Firstly, it would be nice if your commit messages were something suggestive of the work you've done. "hello" is not very suggestive.

Secondly, I know that the pages for flights, accommodation and venues are supposed to look similar, but copying Szabi's code and just changing a few things is not very fair, let's be honest. 

The restaurant listings are missing the details button. Instead of the button taking you to a new page, you could make it a pop-up about the details. Perhaps list the type of event it is, the menu in case of restaurants, or other additions you can think of.

**Comment by jabarca99** [comment]
Firstly, I wanst understanding how it works the commit page so it wasnt on purpose my "hello" message, thats why i commented here the things that i did.

Secondly, I took the Szabi's code as a reference because is my first time using Vue and if it has to look similar i dont think its a bad practice at all to reuse part of his code, but i can change it if you or he are mad about it.

Finally, yes i havent finished my work yet, I was waiting you to check my code if it was nice to you, now i will do all the nexts parts  of the work including the details button. Thanks for the suggestion by the way.

**Review by Mexaby — COMMENTED** [review]
Search function seems to work well, and the pop-up looks nice. Good job.

**Review by Mexaby — APPROVED** [review]
Good work!

**Pull request merged**
